# Codeship specific docker compose file
version: "2"

services:
  micro_golang:
    # Additional build context options compared to prod
    build:
      context: ./tests
      dockerfile: Dockerfile
    image: twhiston/micro-golang:test-build